### ISSUE TITLE
fromdicts(...).header()

### ISSUE THREAD

**Issue by alimanfoo** [petl-developers/petl#391]
raises TypeError; originally reported in #385

**Comment by dnicolodi** [comment]
The issue arises because `DictsView`'s constructor assigns a `header` instance variable that overwrites the base class `header()` method. The only possible solution is to rename the instance variable, however, this may be seen as a backward incompatible change (I don't know Petl's code conventions, but the fact that the member name is not prefixed with an underscores makes the member public interface accordingly to broad Python's conventions).

If renaming the class member is not an issue, I can prepare a PR.

**Comment by dnicolodi** [comment]
Oh, the issue is already solved by #555 which forgot a "Fixes: #391" in its commit message...
