### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by nvn1729** [petl-developers/petl#526]
Hello, I have a security issue to report. Can you please provide a contact to report it to or instructions on how to report it? Thanks!

**Comment by juarezr** [comment]
Hello @nvn1729 ,

Please send a message to my personal m4iL.

name: juarezr 
provider: gmail

**Comment by nvn1729** [comment]
Hi @juarezr  message sent.

**Comment by juarezr** [comment]
It's unlikely a security issue would be exploited because:

- `petl` isn't directly exposed to end users. But apps and scrips using `petl` may be.
-  It's not common neither recommended running as root or as high priviledged user with apps using `petl`
- Communication in `petl` uses cases are likely to be unidirecional, like from a local/remote source or from local data to remote. `petl` by itself doen't answer to remote requests.
- `ETL` programs are not commonly exposed to remote calls.

**Comment by juarezr** [comment]
Related to #526 and #527.

Fixed in [v1.6.8](https://github.com/petl-developers/petl/releases/tag/v1.6.8).
