### ISSUE TITLE
Documentation says "tested with Python versions 2.7 and 3.4-3.6" but setup.py also has 3.6+

### ISSUE THREAD

**Issue by benstroud** [petl-developers/petl#556]
The doc at https://petl.readthedocs.io/en/stable/intro.html has the sentence "petl has been tested with Python versions 2.7 and 3.4-3.6 under Linux and Windows operating systems." but I notice that setup.py (v1.7.4) lists 3.7 and 3.8. Is petl now tested and stable for these Python versions as well? Thank you.

**Comment by juarezr** [comment]
Hi @benstroud,

- This [documentation](https://petl.readthedocs.io/en/stable/changes.html) are stale at version [1.6.8](https://petl.readthedocs.io/en/stable/changes.html) but `petl` is at version [1.6.4](https://github.com/petl-developers/petl/releases/tag/v1.7.4) right now. This is due to an unresolved issue between travis-ci.org and readthedocs.org.
- The statement in the [docs](https://petl.readthedocs.io/en/stable/intro.html) was written when `petl` was at some version close to 1.4. There were few changes to the core since that.
- The GitHub actions CI is [testing](https://github.com/petl-developers/petl/actions/runs/691917540) `petl` against `python` 2.7, 3.6 - 3.9. Although I have found some minor issues with `python3.9` tests.
- I have used python3.8 in production for some months already.
- Please open an issue here if you find any issues.
