### ISSUE TITLE
PyPI petl not up to date (1.7.4 vs 1.7.5)

### ISSUE THREAD

**Issue by arturponinski** [petl-developers/petl#583]
I've noticed that the latest available version of petl on PyPi is 1.7.4: https://pypi.org/project/petl/
However, here on github the version is 1.7.5 release on Oct 15, 2021. Is there any particular reason, this has not been released? Would you be able to release the latest version at your earliest convenience? 
Thanks in advance.

**Comment by juarezr** [comment]
Hi @arturponinski,

This happened because the release pipeline was using Travis-ci.org free service. But it was discontinued some time ago.

If I had the credentials to PyPI account, I would already have fixed with a new pipeline in github.com actions.

I sent a message to @alimanfoo but no he hasn't answered yet. Maybe he missed.

**Comment by alimanfoo** [comment]
Hi @juarezr, so sorry for slow reply, if you could send me your PyPI user name I'd be happy to add you as a maintainer.

**Comment by juarezr** [comment]
Hi @alimanfoo,

Glad to see you back here.

After [travis-ci.org](https://travis-ci.org/) ceased working, all `petl` CD stopped working:

- [Github release](https://github.com/petl-developers/petl/releases/tag/v1.7.5) is at [v1.7.5](https://github.com/petl-developers/petl/releases/tag/v1.7.5)
- [PyPI](https://pypi.org/project/petl) is at [v1.7.4](https://github.com/petl-developers/petl/releases/tag/v1.7.4)
- [readthedocs](https://petl.readthedocs.io/en/stable/) is at [v1.68](https://petl.readthedocs.io/en/stable/changes.html)
- [Conda Forge](https://anaconda.org/conda-forge/petl) is at [v1.7.4](https://anaconda.org/conda-forge/petl)

I see that we need to step in to fix all of them. I hope that with your help we can get all working.

Meanwhile:

- I have been creating an alternative CI using [Github Actions](https://github.com/petl-developers/petl/actions).
- So far it has been testing the same set of tests as  [travis-ci.org](https://travis-ci.org/) did plus:
  - It runs tests in [Windows](https://github.com/petl-developers/petl/runs/4997908501?check_suite_focus=true) like [Appveyor](https://ci.appveyor.com/project/petl-developers/petl/history) does.
  - It runs [additional tests](https://github.com/petl-developers/petl/runs/4997908391?check_suite_focus=true#step:10:1) for covering `petl` [database](https://petl.readthedocs.io/en/stable/io.html#databases) integration using docker.
  - It runs [additional tests](https://github.com/petl-developers/petl/runs/4997908391?check_suite_focus=true#step:9:1) for covering `petl` [remote filesystem](https://petl.readthedocs.io/en/stable/io.html#remote-i-o-helper-classes) integration with [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) using docker.
  - It runs [additional tests](https://github.com/petl-developers/petl/runs/4997908612?check_suite_focus=true#step:13:1) for covering MacOS.
 - Coverage stays at the same level as [before](https://coveralls.io/jobs/93575409).

Also, I would like to hear your opinion about:

- Migrating the deployment process for releases of `PyPI`, `Conda Forge` and `readthedocs.org` to  [Github Actions](https://github.com/petl-developers/petl/actions)
- Guidelines for `petl` evolution, because we have some worthy contributions like:
  - @arturponinski migration from `nosetests` to pytest #584 ready to landing
  - POC for adding typing to `petl` functions on #559
  - POC for dropping support for EOL Python 2.7 on #563 
 - Onboard of new maintainers, as I'm busier than before. (@arturponinski  looks like a promising volunteer if he would like 😄 )

#### Accounts

- PyPI username:
  - [juarezr](https://pypi.org/user/juarezr)
- [readthedocs.org](https://readthedocs.org): 
  - juarezr
- Conda Forge 
  - via [petl-feedstock](https://github.com/petl-developers/petl-feedstock)

**Comment by arturponinski** [comment]
I would be more than happy to be part of petl as a maintainer and push petl it to 2.0 according to roadmap posted by @alimanfoo here: https://groups.google.com/g/python-etl/c/0EOmiTOdrUE/m/c1vTuMGjDAAJ

**Comment by juarezr** [comment]
> I would be more than happy to be part of petl as a maintainer and push petl it to 2.0 according to roadmap posted by @alimanfoo here: https://groups.google.com/g/python-etl/c/0EOmiTOdrUE/m/c1vTuMGjDAAJ

- Nice to hear that!
- I think that after your PR #584 we are getting pretty close to 2.0
- A killer feature to make the most of the compatibility break introduced by `v2.0` would be #560 ( #559 ) #274 :smile:

**Comment by alimanfoo** [comment]
Hi @juarezr,

> * I have been creating an alternative CI using [Github Actions](https://github.com/petl-developers/petl/actions).
> * So far it has been testing the same set of tests as  [travis-ci.org](https://travis-ci.org/) did plus:
>   
>   * It runs tests in [Windows](https://github.com/petl-developers/petl/runs/4997908501?check_suite_focus=true) like [Appveyor](https://ci.appveyor.com/project/petl-developers/petl/history) does.
>   * It runs [additional tests](https://github.com/petl-developers/petl/runs/4997908391?check_suite_focus=true#step:10:1) for covering `petl` [database](https://petl.readthedocs.io/en/stable/io.html#databases) integration using docker.
>   * It runs [additional tests](https://github.com/petl-developers/petl/runs/4997908391?check_suite_focus=true#step:9:1) for covering `petl` [remote filesystem](https://petl.readthedocs.io/en/stable/io.html#remote-i-o-helper-classes) integration with [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) using docker.
>   * It runs [additional tests](https://github.com/petl-developers/petl/runs/4997908612?check_suite_focus=true#step:13:1) for covering MacOS.
> * Coverage stays at the same level as [before](https://coveralls.io/jobs/93575409).

All sounds great.
 
> Also, I would like to hear your opinion about:
> 
> * Migrating the deployment process for releases of `PyPI`, `Conda Forge` and `readthedocs.org` to  [Github Actions](https://github.com/petl-developers/petl/actions)

SGTM, whatever you think would be most convenient.

> * Guidelines for `petl` evolution, because we have some worthy contributions like:
>   
>   * @arturponinski migration from `nosetests` to pytest [Migrate to pytest #584](https://github.com/petl-developers/petl/pull/584) ready to landing
>   * POC for adding typing to `petl` functions on [[POC] added typing to materialize (breaks py27 tests) #559](https://github.com/petl-developers/petl/pull/559)
>   * POC for dropping support for EOL Python 2.7 on [Drop support for EOL Python 2.7 #563](https://github.com/petl-developers/petl/pull/563)
> * Onboard of new maintainers, as I'm busier than before. (@arturponinski  looks like a promising volunteer if he would like smile )

FWIW very happy for you to grant maintainer status to contributors as you see fit. 

@arturponinski it's a pleasure to meet you!

> #### Accounts
> * PyPI username:
>   
>   * [juarezr](https://pypi.org/user/juarezr)
> * [readthedocs.org](https://readthedocs.org):
>   
>   * juarezr
> * Conda Forge
>   
>   * via [petl-feedstock](https://github.com/petl-developers/petl-feedstock)

I've added you to PyPI and RTFD, I think you're already on the conda-forge feedstock.

Please let me know if there's anything else I can help with :cherry_blossom:

**Comment by juarezr** [comment]
Hi @alimanfoo,

I going to check everything and return if there is any other problem.
Thanks for your time.

Hi @ arturponinski,

I'll add you as maintainer of this repository also. Welcome!

**Comment by juarezr** [comment]
Update:

- Migrated release from discontinued [travis-ci.org](https://travis-ci.org/github/petl-developers/petl/jobs/751914189) to a brand new CD using [Github Action](https://github.com/petl-developers/petl/blob/master/.github/workflows/publish-release.yml) in #593 
- Released version v1.7.6 to [PyPI](https://pypi.org/project/petl/1.7.6/)
- Fixed [readthedocs.org](https://petl.readthedocs.io/en/stable/) build

**Comment by juarezr** [comment]
TODO:

- Waiting for [petl-feedstock]() trigger a new release in conda forge
- Remove hooks of:
  - travis-ci.org
  - AppVeyor
  - Both testing and release are now on Github Actions
 - Update the badges on readme.md
 - Cleanup outdated files and docs on repository

**Comment by arturponinski** [comment]
That's amazing news! Impressive work @juarezr

**Comment by juarezr** [comment]
- After the [release](https://pypi.org/project/petl/1.7.6/) on PyPI was fixed, [conda-forge/petl-feedstock](https://github.com/conda-forge/petl-feedstock/pull/23) detected and triggered its PR, as usual. 🎉 
- So soon we may have [v1.7.6](https://github.com/petl-developers/petl/releases/tag/v1.7.6) on [Conda Forge](https://anaconda.org/conda-forge/petl) too.
- Releasing [v1.7.5](https://github.com/petl-developers/petl/releases/tag/v1.7.5) will demand manual intervention.  But right now I'm a little busy for making this hanppen.

**Comment by arturponinski** [comment]
Still some nosetests leftovers https://github.com/conda-forge/petl-feedstock/blob/master/recipe/meta.yaml

**Comment by juarezr** [comment]
Investigating [failure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=452023&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=523):

``` bash
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/petl_1643806652129/test_tmp
import: 'petl'
import: 'petl'
+ pytest --verbose petl
============================= test session starts ==============================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- $PREFIX/bin/python
cachedir: .pytest_cache
rootdir: $SRC_DIR
collecting ... collected 0 items

============================ no tests ran in 0.00s =============================
ERROR: file or directory not found: petl

Tests failed for petl-1.7.6-pyh6c4a22f_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by arturponinski** [comment]
@juarezr wouldn't this: https://github.com/petl-developers/petl/pull/596/files resolve the issue of missing 1.7.5 in PyPI ?
It would be beneficial in case the action failed for whatever reason.

**Comment by juarezr** [comment]
- It would be very interesting to have such a procedure
- I didn't look how it works yet

**Comment by juarezr** [comment]
- Release [v1.7.7](https://github.com/petl-developers/petl/releases/tag/v1.7.7) available in [Conda Forge](https://anaconda.org/conda-forge/petl)
- Fixed [petl-feedstock](https://github.com/conda-forge/petl-feedstock) on conda-forge/petl-feedstock#27
- Next release should work transparently by:
  - Tagging a SemVer version on this github repository (v1.7.8)
 - Releases v1.7.5 and v1.7.6 missing in Conda Forge (v1.7.5 also missing on PyPI)

**Comment by juarezr** [comment]
- Update: [v1.7.5]() uploaded to [PyPI project repository](https://pypi.org/project/petl/1.7.5/)
- Waiting for [regro-cf-autotick-bot](https://github.com/regro-cf-autotick-bot) to trigger the [conda-build](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html) build/import on [conda-forge/petl-feedstock](https://github.com/conda-forge/petl-feedstock/actions/workflows/automerge.yml) and uploading to [Conda Forge](https://anaconda.org/conda-forge/petl)
